name: Linux Test

on:
  push:
    branches: [ github_action ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: ./engine
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install
      - name: Pyinstaller
        working-directory: ./engine
        run: pipenv run pyinstaller -w --noconfirm Extractor.py dllive.py dlstories.py
      - run: npm run build
