name: Mac Legacy Action

on:
  push:
    branches: [main]

jobs:
  createRelease:
    name: Create Release
    runs-on: 'ubuntu-latest'
    if: "contains(github.event.head_commit.message, '-legacy')"
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: test
          release_name: Release ${{ steps.create_release.outputs.upload_url }}
          draft: true
          prerelease: false
  Release:
    runs-on: macos-10.15
    needs: createRelease
    if: "contains(github.event.head_commit.message, '-legacy')"
    steps:
      - uses: actions/checkout@v2
      ###NODE
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: get-npm-version
        id: package-version
        uses: nyaayaya/package-version@v1
      - uses: suisei-cn/actions-download-file@v1
        with:
          url: 'https://github.com/JCGithu/Sinon/raw/main/MacLegacy.zip'
          target: engine/
      - name: Mac Legacy Unzip
        working-directory: ./engine
        run: unzip MacLegacy.zip
      ###PACKAGING
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
      - name: Decompress
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq ./dist/Sinon-${{ env.PACKAGE_VERSION }}-mac.zip -d ./dist/Sinon-${{ env.PACKAGE_VERSION }}-mac
      - name: rename Mac Legacy
        run: |
          cd dist
          cd Sinon-${{ env.PACKAGE_VERSION }}-mac
          chmod +x Sinon.app/Contents/MacOS/*
          cd ..
          zip -r Sinon-${{ env.PACKAGE_VERSION }}-mac-Legacy.zip Sinon-${{ env.PACKAGE_VERSION }}-mac
      ###UPLOADING
      - name: Upload
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.createRelease.outputs.upload_url }}
          asset_path: ./dist/Sinon-${{ env.PACKAGE_VERSION }}-mac-Legacy.zip
          asset_name: Sinon-${{ env.PACKAGE_VERSION }}-mac-Legacy.zip
          asset_content_type: application/zip
