name: Releases Action

on:
  push:
    branches: [ github_action ]

jobs:
  Release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: ./engine
        run: |
          python -m pip install --upgrade pip
          python -m pip install pipenv
          python -m pipenv install
          python -m pipenv update youtube-dl
      - name: Pyinstaller Linux
        working-directory: ./engine
        run: pipenv run pyinstaller -w --noconfirm Extractor.py dllive.py dlstories.py
        if: matrix.os == 'ubuntu-latest'
      - name: Pyinstaller Windows
        working-directory: ./engine
        run: pipenv run pyinstaller -w --noconfirm Extractor.py dllive.py dlstories.py
        if: matrix.os == 'windows-latest'
      - name: Pyinstaller Mac
        working-directory: ./engine
        run: pipenv run pyinstaller --debug all --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' --onedir extractor.py dllive.py dlstories.py
        if: matrix.os == 'macos-latest'
      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
      - name: Upload to a release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: ./dist
          GITHUB_TOKEN: ${{ secrets.github_token }}